name: cli-jobs-pipelines-advertising-sales
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/2300 * * *"
  pull_request:
    branches:
      - main
      - sdk-preview
    paths:
      - jobs/advertising_sales_pipeline/**
      - .github/workflows/main.yml
      - run-pipeline-jobs.sh
      - setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      continue-on-error: true
    - name: run job
      run: bash -x ../../run-job.sh pipeline.yml
      working-directory: jobs/advertising_sales_pipeline
